import { type AppTheme } from './themes';

export interface Tool {
  name: string;
  slug: string;
  iconKey: string;
  theme: AppTheme;
  category: string;
}

export const TOOLS: Tool[] = [
  { name: 'Merge PDF Online', slug: 'merge-pdf', iconKey: 'FileText', theme: 'blue', category: 'PDF' },
  { name: 'Compress PDF Online', slug: 'compress-pdf', iconKey: 'Minimize2', theme: 'purple', category: 'PDF' },
  { name: 'Split PDF Online', slug: 'split-pdf', iconKey: 'SplitSquareHorizontal', theme: 'orange', category: 'PDF' },
  { name: 'PDF to Word Converter', slug: 'pdf-to-word', iconKey: 'FileOutput', theme: 'cyan', category: 'Convert' },
  { name: 'Word to PDF Converter', slug: 'word-to-pdf', iconKey: 'FileText', theme: 'indigo', category: 'Convert' },
  { name: 'JPG to PDF Converter', slug: 'jpg-to-pdf', iconKey: 'ImageIcon', theme: 'pink', category: 'Image' },
  { name: 'PDF to JPG Converter', slug: 'pdf-to-jpg', iconKey: 'Maximize2', theme: 'rose', category: 'Image' },
  { name: 'Image Compressor', slug: 'image-compressor', iconKey: 'FileArchive', theme: 'green', category: 'Image' },
  { name: 'PNG to JPG Converter', slug: 'png-to-jpg', iconKey: 'ImageIcon', theme: 'emerald', category: 'Image' },
  { name: 'JPG to PNG Converter', slug: 'jpg-to-png', iconKey: 'ImageIcon', theme: 'pink', category: 'Image' },
  { name: 'PNG to WebP Converter', slug: 'png-to-webp', iconKey: 'ImageIcon', theme: 'emerald', category: 'Image' },
  { name: 'WebP to PNG Converter', slug: 'webp-to-png', iconKey: 'ImageIcon', theme: 'cyan', category: 'Image' },
  { name: 'JPG to WebP Converter', slug: 'jpg-to-webp', iconKey: 'ImageIcon', theme: 'pink', category: 'Image' },
  { name: 'WebP to JPG Converter', slug: 'webp-to-jpg', iconKey: 'ImageIcon', theme: 'cyan', category: 'Image' },
  { name: 'PNG to AVIF Converter', slug: 'png-to-avif', iconKey: 'ImageIcon', theme: 'emerald', category: 'Image' },
  { name: 'JPG to AVIF Converter', slug: 'jpg-to-avif', iconKey: 'ImageIcon', theme: 'pink', category: 'Image' },
  { name: 'AVIF to PNG Converter', slug: 'avif-to-png', iconKey: 'ImageIcon', theme: 'indigo', category: 'Image' },
  { name: 'AVIF to JPG Converter', slug: 'avif-to-jpg', iconKey: 'ImageIcon', theme: 'indigo', category: 'Image' },
  { name: 'SVG to PNG Converter', slug: 'svg-to-png', iconKey: 'ImageIcon', theme: 'orange', category: 'Image' },
  { name: 'SVG to JPG Converter', slug: 'svg-to-jpg', iconKey: 'ImageIcon', theme: 'orange', category: 'Image' },
  { name: 'SVG to WebP Converter', slug: 'svg-to-webp', iconKey: 'ImageIcon', theme: 'orange', category: 'Image' },
  { name: 'MP4 to MP3 Converter', slug: 'mp4-to-mp3', iconKey: 'Music', theme: 'violet', category: 'Audio' },
  { name: 'SIP Calculator', slug: 'sip-calculator', iconKey: 'TrendingUp', theme: 'blue', category: 'Finance' },
  { name: 'Compound Interest', slug: 'compound-interest-calculator', iconKey: 'Calculator', theme: 'emerald', category: 'Finance' },
  { name: 'FD Calculator', slug: 'fd-calculator', iconKey: 'Landmark', theme: 'purple', category: 'Finance' },
  { name: 'Mutual Fund Calculator', slug: 'mutual-fund-calculator', iconKey: 'BarChart3', theme: 'cyan', category: 'Finance' },
  { name: 'PPF Calculator', slug: 'ppf-calculator', iconKey: 'ShieldCheck', theme: 'indigo', category: 'Finance' },
  { name: 'RD Calculator', slug: 'rd-calculator', iconKey: 'Repeat', theme: 'orange', category: 'Finance' },
  { name: 'Standard Calculator', slug: 'standard-calculator', iconKey: 'Calculator', theme: 'blue', category: 'Math' },
  { name: 'Scientific Calculator', slug: 'scientific-calculator', iconKey: 'Divide', theme: 'indigo', category: 'Math' },
  { name: 'Differentiation Tool', slug: 'differentiation-calculator', iconKey: 'Variable', theme: 'purple', category: 'Math' },
  { name: 'Integration Tool', slug: 'integration-calculator', iconKey: 'Sigma', theme: 'emerald', category: 'Math' },
  { name: 'Equation Solver', slug: 'equation-solver', iconKey: 'X', theme: 'rose', category: 'Math' },
  { name: 'Quadratic Equation Solver', slug: 'quadratic-solver', iconKey: 'ChevronRight', theme: 'orange', category: 'Math' },
  { name: 'Matrix Calculator', slug: 'matrix-calculator', iconKey: 'Grid', theme: 'cyan', category: 'Math' },
  { name: 'Statistics Calculator', slug: 'statistics-calculator', iconKey: 'BarChart3', theme: 'blue', category: 'Math' },
  { name: 'GCD & LCM Calculator', slug: 'gcd-lcm-calculator', iconKey: 'Minimize2', theme: 'green', category: 'Math' },
  { name: 'Percentage Calculator', slug: 'percentage-calculator', iconKey: 'Percent', theme: 'pink', category: 'Math' },
  { name: 'Fraction Calculator', slug: 'fraction-calculator', iconKey: 'Divide', theme: 'orange', category: 'Math' },
  { name: 'Logarithm Tool', slug: 'logarithm-calculator', iconKey: 'Binary', theme: 'orange', category: 'Math' },
  { name: 'Unit Converter', slug: 'unit-converter', iconKey: 'Ruler', theme: 'blue', category: 'Utility' },
  { name: 'BMI Calculator', slug: 'bmi-calculator', iconKey: 'Activity', theme: 'rose', category: 'Utility' },
  { name: 'Age Calculator', slug: 'age-calculator', iconKey: 'Calendar', theme: 'emerald', category: 'Utility' },
  { name: 'Binary Converter', slug: 'binary-converter', iconKey: 'Cpu', theme: 'indigo', category: 'Utility' },
  { name: 'Random Number Generator', slug: 'random-generator', iconKey: 'Shuffle', theme: 'purple', category: 'Utility' },
  { name: 'Roman Numeral Converter', slug: 'roman-numerals', iconKey: 'Hash', theme: 'orange', category: 'Utility' },
  { name: 'QR Code Generator', slug: 'qr-code-generator', iconKey: 'QrCode', theme: 'emerald', category: 'Utility' },
  { name: 'PDF Viewer', slug: 'pdf-viewer', iconKey: 'FileText', theme: 'emerald', category: 'PDF' },
  { name: 'Image Color Palette', slug: 'image-color-palette-generator', iconKey: 'Palette', theme: 'emerald', category: 'Utility' },
  { name: 'Loan Calculator', slug: 'loan-calculator', iconKey: 'Wallet', theme: 'emerald', category: 'Finance' },
  { name: 'Discount Calculator', slug: 'discount-calculator', iconKey: 'Tag', theme: 'rose', category: 'Finance' },
  { name: 'Margin Calculator', slug: 'margin-calculator', iconKey: 'Percent', theme: 'blue', category: 'Finance' },
  { name: 'Sales Tax Calculator', slug: 'sales-tax-calculator', iconKey: 'Receipt', theme: 'orange', category: 'Finance' },
  { name: 'Online Compiler', slug: 'online-compiler', iconKey: 'Code', theme: 'emerald', category: 'Utility' },
];
